"""empty message

Revision ID: 1a5bc5c15a6e
Revises: ead045fbb067
Create Date: 2024-03-02 01:00:05.677255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5bc5c15a6e'
down_revision = 'ead045fbb067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminFirstName', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('adminFirstName')

    # ### end Alembic commands ###
